// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FullcalendarController from "./fullcalendar_controller"
application.register("fullcalendar", FullcalendarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotyfController from "./notyf_controller"
application.register("notyf", NotyfController)

import ModalContentController from "./modal_content_controller"
application.register("modal-content", ModalContentController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
