// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotyfController from "./notyf_controller"
application.register("notyf", NotyfController)

import SlideoverContentController from "./slideover_content_controller"
application.register("slideover-content", SlideoverContentController)

import SlideoverController from "./slideover_controller"
application.register("slideover", SlideoverController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import FullCalendarController from "./fullcalendar_controller"
application.register("fullcalendar", FullCalendarController)
